### ISSUE TITLE
API Key removed on godam.io and demo.godam.io

### ISSUE THREAD

**Issue by subodhr258** [rtCamp/godam#1290]
## Overview
After v1.4.5, the API key on godam.io and demo.godam.io was removed, specifically the `rtgodam-api-key` key in the `wp_options` table disappears when the API request to Frappe fails.

Expected outcome: API Key should never be removed after it is saved successfully once.
## Screenshot
<img width="1465" height="704" alt="Image" src="https://github.com/user-attachments/assets/d195e47f-26a0-4b14-a80c-d18371abdeef" />

**Comment by nitun** [comment]
API key should never be removed; it should show the message if expired.

**Comment by subodhr258** [comment]
After some debugging I found that the Frappe server was returning a 503 error with no body or message. This needs debugging on Frappe end.

## Raw response from Frappe server: 
```html
<html> 
<head><title>503 Service Temporarily Unavailable</title></head>
 <body> 
<center><h1>503 Service Temporarily Unavailable</h1></center>
 <hr>
<center>nginx/1.29.1</center> 
</body> 
</html>
```

## Screenshot:

<img width="1457" height="787" alt="Image" src="https://github.com/user-attachments/assets/10eeea37-dba7-4c6c-87c9-7896e12741f5" />

**Comment by subodhr258** [comment]
We need to check if the issue on demo.godam.io and godam.io is resolved, the rtbiz.io GoDAM plugin has been updated to 1.4.5.

If the issue doesn't persist until tomorrow, we could safely close this ticket @hashibhere. I have activated the API Keys on both sites.

**Comment by hashibhere** [comment]
Issue still persists:

Site: `godam.io`

<img width="1368" height="798" alt="Image" src="https://github.com/user-attachments/assets/faa1f205-1b51-4d57-aa5a-109bcf688636" />

cc: @subodhr258

**Comment by hashibhere** [comment]
The issue is no longer present, if I see it again will report back here. For now, I am closing this issue.

**Comment by subodhr258** [comment]
@kishan-gondaliya-7270 the hotfix is merged, please test for release.

We have handled these cases from frappe:

- 200 success
- 200 error
- Other cases:
  - API Key exists - preserve data
  - API Key doesn't exist - send error

**Comment by subodhr258** [comment]
@kishan-gondaliya-7270 the PR is merged and ready for QA.

I have reduced the time interval and updated the code on this site: https://test-godam-key.rt.gw/ (provided access to you on ED)
Will keep checking if API key gets removed.
